// For adding custom fonts with other frameworks, see:
// https://tailwindcss.com/docs/font-family
import type { Metadata } from "next";
import { Outfit, Alegreya, JetBrains_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs"
import { dark } from "@clerk/ui/themes"
import "./globals.css";

const fontSans = Outfit({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Alegreya({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        cssLayerName: "clerk",
        theme: dark,
        variables: {
          colorBackground: "var(--color-background)",
          colorForeground: "var(--color-foreground)",

          colorPrimary: "var(--color-primary)",
          colorPrimaryForeground: "var(--color-primary-foreground)",

          colorNeutral: "var(--color-muted-foreground)",

          colorInput: "var(--color-input)",
          colorInputForeground: "var(--color-foreground)",

          colorDanger: "var(--color-primary)",
          colorSuccess: "var(--color-primary)",
          colorWarning: "var(--color-primary)",

          borderRadius: "var(--radius-lg)",
          fontFamily: "var(--font-sans)",
        },

        elements: {
          card:
            "bg-card text-card-foreground border border-border shadow-md rounded-xl",

          headerTitle: "text-foreground font-semibold",
          headerSubtitle: "text-muted-foreground",

          formButtonPrimary:
            "bg-primary text-primary-foreground hover:opacity-90",

          formFieldInput:
            "bg-input text-foreground border border-border focus:ring-primary",

          footerActionLink:
            "text-primary hover:opacity-80",

          socialButtonsBlockButton:
            "bg-card text-foreground border border-border hover:bg-accent",
        },
      }}
    >
      <html lang="en" className="dark text-sm">
        <body className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}